{% set name = "Flask-OAuthlib" %}
{% set version = "0.9.5" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "cbfe835902569909a19828582c3381148995ad677243016ccad9c951acf69406" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - flask
    - oauthlib >=1.1.2,!=2.0.3,!=2.0.4,!=2.0.5,<3.0.0
    - requests-oauthlib >=0.6.2

test:
  imports:
    - flask_oauthlib
    - flask_oauthlib.contrib
    - flask_oauthlib.contrib.client
    - flask_oauthlib.provider

about:
  home: https://github.com/lepture/flask-oauthlib
  license_file: LICENSE
  license: BSD 3-Clause
  license_family: BSD
  summary: 'OAuthlib for Flask'
  dev_url: https://github.com/lepture/flask-oauthlib
  doc_url: https://flask-oauthlib.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
