# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "EYmoHd7c/LwTd6pF1TYZsTGV+2a7urFEa6ckj9pKwL0zxfkCLcSMZ5PlfT/u7aOIM6AIbWhDEGzr6C2V41/hs+e6kguAgAUqRuD3gPEK1/Y4UnahjL7B8H8c/TXVRPwigFSarkv6977Blov1m4oVikBbHGxguoAZLpvigDZcpRkSGkbmVPGR+DRdy0VbpOw0EZCOtkimsdAv3M2UQ4TOLQ4vx+T05UYPJ/r9AGXAcHOqL76r0eqz08wmUH2nQm71enr7LXThPSkGrx+YGohJ5keNO6diXsu1RPhavUxnviMgAAsijk+oGGTLLdYnDFYGZBrTQi6stPof/FTUSdRjrHSwhdQw+ViyBYWkoML5jByHAPjFrZSHPLP6l1EoNh1EKFlOxGuL5GvoKMAJw/DgnRDBySVTD1dbPBAKWflcEoq1Yi+LR6OaJ4KXVpi9eHPPJMgegH/jaq1sIzUsFNlqhYNjgis+UWtZXlaOAaHfUU5857kSOqdFezTgU5Nr6wTwSkjrrdHCOWeacbmLhA64Z94sPXa7zXQjLF0PLeOnEsalZ/n3dx9R+Myrhs5Nd1GgsFZ+8k9lVKziePZ0vRZxkyBIOeUe4JFOWRJU9y3Z7QYZsB6Gdf9nrtcqsDYCe+nWWsa4L+XrTQcQX6SacoVozbikb1+SeLIV0g64HG4bO60="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
