# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "cR5J/G7yw3u8qddpXNUB2peHxnTev1RAbWGpiqdPGxhf0h6al4bmDvAYnyL+a35qU9FqgyJQBC7Zfrc3ZGRl35fgCFI3uQfFfLTDInWCiJtMvLHx1hDOPqOKCzq68tHEbPgufPvCxDhzbc6S3MNlCB3/raNf+xODrac09ScN+MhevPmhv5/oo+AUGj3zxucUNSEuGz0NPeZ8+/XpVtpTQe1TaXknVB6E++QGiL8R4KeOTK0am1qOTwzM5+p8YcGqhS19FpIjtQceCSKMu1WsuvEb6cuzlFl0UZBSuXkP9lBTv9pqu8H/IIMFqzfK94qWyEXnwUqsroPAaoK1euc2rIz8GBohDDfJZGnU9/AjoNaYXLROIn9ZFZVGA7IGDRv92uf3o1CpOa9ne18SuzMlwsjqflkTXzguzi2PVgYZJ4Bv26wKD57GCWlZuf6+XLoQO48q4ysq+h3L+M2sEBzen0JiTUJp1muAlc+QQjr/k380VSEOy4hYK3YpmBCaL2KA4V4OuQIXRzDyy36ZwMuW4Sy45hGKRpYUh2hw0OIIXr7913FKhiRQ3SSMnVJn5T8MryGA5XNk8xGEB9/S33ESFD4nh4t5NErPIwg3YSO1oKltqwQknoYLlEly8z4VobMlpCFJLoomJkhrMGbHFab+3IWJco9Mc1hz6fcTypUe4ek="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
