# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "cR5J/G7yw3u8qddpXNUB2peHxnTev1RAbWGpiqdPGxhf0h6al4bmDvAYnyL+a35qU9FqgyJQBC7Zfrc3ZGRl35fgCFI3uQfFfLTDInWCiJtMvLHx1hDOPqOKCzq68tHEbPgufPvCxDhzbc6S3MNlCB3/raNf+xODrac09ScN+MhevPmhv5/oo+AUGj3zxucUNSEuGz0NPeZ8+/XpVtpTQe1TaXknVB6E++QGiL8R4KeOTK0am1qOTwzM5+p8YcGqhS19FpIjtQceCSKMu1WsuvEb6cuzlFl0UZBSuXkP9lBTv9pqu8H/IIMFqzfK94qWyEXnwUqsroPAaoK1euc2rIz8GBohDDfJZGnU9/AjoNaYXLROIn9ZFZVGA7IGDRv92uf3o1CpOa9ne18SuzMlwsjqflkTXzguzi2PVgYZJ4Bv26wKD57GCWlZuf6+XLoQO48q4ysq+h3L+M2sEBzen0JiTUJp1muAlc+QQjr/k380VSEOy4hYK3YpmBCaL2KA4V4OuQIXRzDyy36ZwMuW4Sy45hGKRpYUh2hw0OIIXr7913FKhiRQ3SSMnVJn5T8MryGA5XNk8xGEB9/S33ESFD4nh4t5NErPIwg3YSO1oKltqwQknoYLlEly8z4VobMlpCFJLoomJkhrMGbHFab+3IWJco9Mc1hz6fcTypUe4ek="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
