travis:
  secure:
    BINSTAR_TOKEN: cR5J/G7yw3u8qddpXNUB2peHxnTev1RAbWGpiqdPGxhf0h6al4bmDvAYnyL+a35qU9FqgyJQBC7Zfrc3ZGRl35fgCFI3uQfFfLTDInWCiJtMvLHx1hDOPqOKCzq68tHEbPgufPvCxDhzbc6S3MNlCB3/raNf+xODrac09ScN+MhevPmhv5/oo+AUGj3zxucUNSEuGz0NPeZ8+/XpVtpTQe1TaXknVB6E++QGiL8R4KeOTK0am1qOTwzM5+p8YcGqhS19FpIjtQceCSKMu1WsuvEb6cuzlFl0UZBSuXkP9lBTv9pqu8H/IIMFqzfK94qWyEXnwUqsroPAaoK1euc2rIz8GBohDDfJZGnU9/AjoNaYXLROIn9ZFZVGA7IGDRv92uf3o1CpOa9ne18SuzMlwsjqflkTXzguzi2PVgYZJ4Bv26wKD57GCWlZuf6+XLoQO48q4ysq+h3L+M2sEBzen0JiTUJp1muAlc+QQjr/k380VSEOy4hYK3YpmBCaL2KA4V4OuQIXRzDyy36ZwMuW4Sy45hGKRpYUh2hw0OIIXr7913FKhiRQ3SSMnVJn5T8MryGA5XNk8xGEB9/S33ESFD4nh4t5NErPIwg3YSO1oKltqwQknoYLlEly8z4VobMlpCFJLoomJkhrMGbHFab+3IWJco9Mc1hz6fcTypUe4ek=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
