travis:
  secure:
    BINSTAR_TOKEN: AX65sbdZIlaPVoG7eLajB8z8bHahrlAqjp8W/aYp0YE1QzvNwe/MQMKPp3GbBPjstxBueEutu1C528BqqtHzQvePAT8Sf1Dz+s5KpY5zFN3XtmE4GGfgdA0yoIBNFTfLB0F1KoNCNG5FuZAKQa76iqNE0KYM6z5hR8NcXqlOC9vb+qKKaf4o94tDuPKE3cPKurNhSTpafoPmbcbi9vQ3vQuGhsYKbmsPY12C1AIXlVwUGWk76T64nMsV7wJof8XXroeASA4f4jGBJIL9TwfRcwHurkVvqXxCRE9NAeEBmWLDVnnGl/vu7Vrq3RUxGlu5q9WEsQKeIkPg5ieAU97k44Q7Vr8YuFzzYk9dxjYm3cz0FT8g6q5qHn/ubICdqW5t1/Us/1R3NCLKXyhGJi1co72Wjyw34Gc8qJsp6YkZBhppTys91KUmLVACNf6xQWsbaQjK4pJ67RO+DZ9e2B7WLyp3b67ox0Uq4nKocOAy651qtB/H9DXP0PZKeaeBq468Fg8dBD4SnLbEtxpDuCHyPNlRzM/UJ1fB3MU6A9KWJeSzpH5rfgyWu8RQAVxfp0cGOQHGlWI3Zhc35L/nMdZ4JXo+eH6b7DNxd3xY7LGB9tW5RYq159jGP0NTTsZ2k23NhV4RfmxhXx1rWFDkANYS2YDNLkzX6Wylu/kzFnEUbXI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
