travis:
  secure:
    BINSTAR_TOKEN: vhiaQHUhoYDDRwmwo78lmzH+N7QZn+U/eUS/EX7bG4eHwZouW2v1W9lq43zNYKv6Y54U39ETMGhprqCpJUwIALQpzeuaFqid4rA5BRdMw3WIOcn3vDGR1WZLnLB3JbWLGCsD6Qj1LeaLIAr4VoZB2Yg8CnY4+/QRR9q3ltrLPy1cWh53TxrAaLpwhYLcsugoz9B3od3qDaReLYDlvek5NcVdMRt3iClp/HxNfYG52SUUyZ9du+tfz4ahxmFjrXQk0U0cGBYYgPrEkjaJlHx++uQyecv7YfQ7tgsUJW9ShxxbUccHQ2V1fPN+qLL5ZKOlte9IOxuwwMyET86peh7Nhq0HXZQg2iaL23PHV63SBldQvo+wwEaz/5+UQgGzX2GsDtGDN2JE9Xeoaw1mRIFvNCa6Eb94b4AmwrMMuwu/qzxIGATRU6OHGYrV80NXKJp7bfq9PGGW0RVvaUSfMq3O0VspJOXDIVX+tqjIP+YVplQmpUPw3ynfeEnmpBggTAiV3ImD6hK4ibRYW8KsP7FqOndLUgmmSgp5LnhAQAfJ1I6RyBOP0d93g32ihBk6wr5eK5F4QBoPf48Y4l3+i+/rqaTnldSF+wMhi+5q8VDc9qMjoHTyRZuAM9m3AUxDA1JYXj+rOmR0p8X1v2eoUNIf4XrdR2D997MaMvqEW7Plxo0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
