travis:
  secure:
    BINSTAR_TOKEN: EYmoHd7c/LwTd6pF1TYZsTGV+2a7urFEa6ckj9pKwL0zxfkCLcSMZ5PlfT/u7aOIM6AIbWhDEGzr6C2V41/hs+e6kguAgAUqRuD3gPEK1/Y4UnahjL7B8H8c/TXVRPwigFSarkv6977Blov1m4oVikBbHGxguoAZLpvigDZcpRkSGkbmVPGR+DRdy0VbpOw0EZCOtkimsdAv3M2UQ4TOLQ4vx+T05UYPJ/r9AGXAcHOqL76r0eqz08wmUH2nQm71enr7LXThPSkGrx+YGohJ5keNO6diXsu1RPhavUxnviMgAAsijk+oGGTLLdYnDFYGZBrTQi6stPof/FTUSdRjrHSwhdQw+ViyBYWkoML5jByHAPjFrZSHPLP6l1EoNh1EKFlOxGuL5GvoKMAJw/DgnRDBySVTD1dbPBAKWflcEoq1Yi+LR6OaJ4KXVpi9eHPPJMgegH/jaq1sIzUsFNlqhYNjgis+UWtZXlaOAaHfUU5857kSOqdFezTgU5Nr6wTwSkjrrdHCOWeacbmLhA64Z94sPXa7zXQjLF0PLeOnEsalZ/n3dx9R+Myrhs5Nd1GgsFZ+8k9lVKziePZ0vRZxkyBIOeUe4JFOWRJU9y3Z7QYZsB6Gdf9nrtcqsDYCe+nWWsa4L+XrTQcQX6SacoVozbikb1+SeLIV0g64HG4bO60=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
